"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const vm = require("node:vm");
const elements = {};
const element = () => ({hidden:false, textContent:"", innerHTML:"", style:{}, children:[], getBoundingClientRect:()=>({width:400})});
for (const id of ["voiceList", "speechProject", "projectSummary", "projectParts"]) elements[id] = element();
const pending = [];
const ctx = vm.createContext({window:{}, document:{querySelector:s=>elements[s.slice(1)]}, getComputedStyle:()=>({rowGap:"10px"}), Date, console});
vm.runInContext(fs.readFileSync("web/static/workspace-features.js", "utf8"),ctx);
const ui = ctx.window.createWorkspaceFeatures({apiJson:url=>new Promise(resolve=>pending.push({url,resolve})),escapeHtml:s=>String(s).replaceAll("<","&lt;"),languageName:s=>s});
assert.deepEqual([...ui.parseTags("Trầm, Kể chuyện, Trầm, ")], ["Trầm","Kể chuyện"]);
assert.throws(()=>ui.parseTags("a".repeat(25)));
assert.throws(()=>ui.parseTags("1,2,3,4,5,6,7,8,9"));
const list = elements.voiceList;
list.children = Array.from({length:8},(_,i)=>({classList:{contains:()=>true},getBoundingClientRect:()=>({height:100+i})}));
ui.fitVoiceList();
assert.equal(list.style.maxHeight,"665px", "six measured rows plus five gaps");
list.children.length=4; ui.fitVoiceList(); assert.equal(list.style.maxHeight,"none");
(async()=>{
  ui.renderProject({job_id:"first",is_project:true,status:"running"});
  ui.renderProject({job_id:"second",is_project:true,status:"running"});
  const manifest = title=>({completed_parts:1,total_parts:2,total_characters:5010,parts:[{index:1,title,characters:5000,status:"done"},{index:2,title:"Next",characters:10,status:"pending"}]});
  pending[1].resolve(manifest("Correct <title>")); await new Promise(resolve=>setImmediate(resolve));
  pending[0].resolve(manifest("Stale project")); await new Promise(resolve=>setImmediate(resolve));
  assert.match(elements.projectParts.innerHTML,/Correct &lt;title>/);
  assert.doesNotMatch(elements.projectParts.innerHTML,/Stale/);
  assert.match(elements.projectParts.innerHTML,/001/);
  assert.match(elements.projectSummary.textContent,/1\/2/);
  ui.renderProject({job_id:"finishing",is_project:true,status:"running"});
  const runningRequest = pending.at(-1);
  const requestsBeforeTerminal = pending.length;
  ui.renderProject({job_id:"finishing",is_project:true,status:"done"});
  ui.renderProject({job_id:"finishing",is_project:true,status:"done"});
  assert.equal(pending.length,requestsBeforeTerminal,"terminal update coalesces behind pending request");
  runningRequest.resolve(manifest("Old running manifest"));
  await new Promise(resolve=>setImmediate(resolve));
  assert.equal(pending.length,requestsBeforeTerminal+1,"inflight completion triggers one terminal manifest refresh");
  pending.at(-1).resolve({...manifest("Final manifest"),completed_parts:2});
  await new Promise(resolve=>setImmediate(resolve));
  assert.match(elements.projectSummary.textContent,/2\/2/);
  assert.match(elements.projectParts.innerHTML,/Final manifest/);
  assert.equal(pending.length,requestsBeforeTerminal+1,"terminal refresh remains bounded");
  ui.renderProject({job_id:"revisited",is_project:true,status:"running"});
  const oldVisit = pending.at(-1);
  ui.renderProject({job_id:"other",is_project:true,status:"running"});
  ui.renderProject({job_id:"revisited",is_project:true,status:"done"});
  const currentVisit = pending.at(-1);
  assert.notEqual(currentVisit,oldVisit);
  currentVisit.resolve(manifest("Current visit"));
  await new Promise(resolve=>setImmediate(resolve));
  oldVisit.resolve(manifest("Stale earlier visit"));
  await new Promise(resolve=>setImmediate(resolve));
  assert.match(elements.projectParts.innerHTML,/Current visit/);
  assert.doesNotMatch(elements.projectParts.innerHTML,/Stale earlier visit/);
  ui.renderProject(null); assert.equal(elements.speechProject.hidden,true);
  const listeners = {};
  const frames = [];
  const navigationElements = Object.fromEntries(["dashboardView","settings","workspaceTitle","workspaceCrumb","voiceListDisclosure","voiceEditCancel","voiceEditForm"].map(id=>[id,{...element(),addEventListener(){}}]));
  Object.assign(elements,navigationElements);
  ctx.window.addEventListener = (name,fn)=>{listeners[name]=fn;};
  ctx.document.querySelectorAll = ()=>[];
  ctx.location = {hash:"#settings"};
  ctx.requestAnimationFrame = fn=>frames.push(fn);
  let jobListMeasurements=0;
  const navigation = ctx.window.createWorkspaceFeatures({syncJobListViewport:()=>{
    assert.equal(elements.dashboardView.hidden,false,"measure only after dashboard becomes visible");
    jobListMeasurements++;
  }});
  navigation.setup();
  assert.equal(elements.dashboardView.hidden,true);
  assert.equal(jobListMeasurements,0);
  ctx.location.hash="#overview";
  listeners.hashchange();
  assert.equal(elements.dashboardView.hidden,false);
  frames.splice(0).forEach(fn=>fn());
  assert.equal(jobListMeasurements,1,"returning from settings remeasures job list without needing SSE");
  console.log("PASS workspace: tags, six-card viewport, terminal manifest refresh, selection isolation, navigation measurement");
})().catch(error=>{console.error(error);process.exitCode=1;});
